### ISSUE TITLE
请问可以在保存激光雷达照片的同时，将普通相机的成像结果一起保存下来吗？

### ISSUE THREAD

**Issue by XueHaoWang-Beijing** [luoxuhai/NightVision#4]
请问可以在保存激光雷达照片的同时，将普通相机的成像结果一起保存下来吗？

**Comment by luoxuhai** [comment]
可以的，这个功能预计下个版本加上，会同时保存2张图片（激光雷达图像和普通图像）

**Comment by XueHaoWang-Beijing** [comment]
> 

感谢回复，另外当前版本保存的激光雷达图像分辨率比较低，这个可以开放高分辨率雷达图像的功能吗

**Comment by luoxuhai** [comment]
最新版本已支持保存普通相机图片功能🧨
