### ISSUE TITLE
希望提升激光相机输出平滑程度

### ISSUE THREAD

**Issue by XueHaoWang-Beijing** [luoxuhai/NightVision#5]
最新版本已支持保存普通相机图片功能🧨

_Originally posted by @luoxuhai in https://github.com/luoxuhai/NightVision/issues/4#issuecomment-1608769921_

感谢开发者及时更新，已购买支持！

希望以后的版本可以提升激光相机输出平滑程度，目前版本边缘锯齿非常严重。

**Comment by luoxuhai** [comment]
会尽快优化🐛
